dist: trusty
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - node
  - "6"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g yarn
install:
  - yarn install --pure-lockfile --ignore-engines
script:
  - yarn ci
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - yarn semantic-release
  - yarn test:report
